apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codegen-0508
  namespace: rhtap
  annotations:
    argocd/app-name: codegen-0508
    janus-idp.io/tekton: codegen-0508
    backstage.io/kubernetes-id: codegen-0508
    backstage.io/kubernetes-namespace: rhtap-app 
    app.kubernetes.io/part-of: codegen-0508
  labels:
    argocd/app-name: codegen-0508
    janus-idp.io/tekton: codegen-0508
    backstage.io/kubernetes-id: codegen-0508
    backstage.io/kubernetes-namespace: rhtap-app 
    app.kubernetes.io/part-of: codegen-0508
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./app/base
    repoURL: https://github.com/stephanie-cy/codegen-0508.git
    targetRevision: main
  destination:
    namespace: codegen-0508
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
