apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: codegen-0508
  janus-idp.io/tekton: codegen-0508
  backstage.io/kubernetes-id: codegen-0508
  backstage.io/kubernetes-namespace: codegen-0508 
  app.kubernetes.io/part-of: codegen-0508
resources: 
#
# - initialize-namespace.yaml
#
- deployment.yaml
- route.yaml
- service.yaml
